# Generated by Django 2.0.13 on 2020-03-28 13:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertiser_name', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to=None)),
                ('short_description', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Register_Company_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_address', models.CharField(max_length=50)),
                ('company_contact', models.CharField(max_length=10)),
                ('company_email', models.CharField(max_length=100)),
                ('company_password', models.CharField(max_length=50)),
                ('company_date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Register_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('email_password', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_category', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('work_type', models.CharField(max_length=20)),
                ('payment_type', models.CharField(max_length=50)),
                ('range_of_salary', models.IntegerField()),
                ('plus_services', models.CharField(max_length=200)),
                ('task_and_responsibilities', models.TextField(max_length=200)),
                ('qualification_and_experience', models.TextField(max_length=300)),
                ('expiry_date', models.DateTimeField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rojgarr.Register_Company_Detail')),
            ],
        ),
    ]
