# Generated by Django 2.0.13 on 2020-05-05 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('employer', models.BooleanField(default=False)),
                ('employe', models.BooleanField(default=False)),
                ('timstamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Advertisement_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertiser_name', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to=None)),
                ('short_description', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Company_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('oppurtunity_rate', models.CharField(max_length=50)),
                ('working_environment', models.CharField(max_length=20)),
                ('management', models.CharField(max_length=20)),
                ('benefits_perks', models.CharField(max_length=20)),
                ('fecilities', models.CharField(max_length=20)),
                ('recommend_other', models.BooleanField()),
                ('salary_rate', models.CharField(max_length=20)),
                ('good_things', models.TextField(max_length=200)),
                ('challeneges', models.TextField(max_length=200)),
                ('company_summary', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('permanent_address', models.CharField(max_length=50)),
                ('temporary_address', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=15)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Register_Company_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_address', models.CharField(max_length=50)),
                ('company_contact', models.CharField(max_length=15)),
                ('company_bussiness', models.CharField(max_length=255)),
                ('address_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_category', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('work_type', models.CharField(max_length=20)),
                ('payment_type', models.CharField(max_length=50)),
                ('range_of_salary', models.IntegerField(blank=True, null=True)),
                ('plus_services', models.CharField(max_length=200)),
                ('task_and_responsibilities', models.TextField(max_length=200)),
                ('qualification_and_experience', models.TextField(max_length=300)),
                ('expiry_date', models.DateTimeField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rojgarr.Register_Company_Detail')),
            ],
        ),
        migrations.AddField(
            model_name='company_review',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rojgarr.Profile'),
        ),
    ]
