# Generated by Django 2.0.13 on 2020-01-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_address', models.CharField(max_length=50)),
                ('skill', models.CharField(max_length=50)),
                ('urgent', models.BooleanField(default=False)),
            ],
        ),
    ]
