# Generated by Django 2.0.13 on 2020-05-20 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rojgarr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_company_detail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
