# Generated by Django 2.0.13 on 2020-05-21 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rojgarr', '0002_auto_20200521_0115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_review',
            old_name='fecilities',
            new_name='facilities',
        ),
    ]
