# Generated by Django 2.0.13 on 2020-02-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rojgarr', '0004_vacancy_detail_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_detail',
            name='full_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
