# Generated by Django 2.0.13 on 2020-02-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rojgarr', '0005_register_detail_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to=None)),
                ('short_description', models.CharField(max_length=200)),
            ],
        ),
    ]
