# Generated by Django 2.0.13 on 2020-05-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rojgarr', '0006_vacancy_detail_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy_detail',
            name='experience_year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
