# Generated by Django 2.0.13 on 2020-05-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rojgarr', '0007_vacancy_detail_experience_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='experience_year',
            field=models.IntegerField(null=True),
        ),
    ]
