# Generated by Django 2.0.13 on 2020-05-28 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rojgarr', '0008_auto_20200524_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement_detail',
            name='date_added',
        ),
    ]
