# Generated by Django 2.0.13 on 2020-05-28 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rojgarr', '0009_remove_advertisement_detail_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement_detail',
            name='image',
        ),
    ]
